name: Update Profile Summary Card

permissions: {}

defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update Profile Summary Card
        run: |
          for theme in github github_dark; do
            wget -q \
              -O "./public/images/profile-summary-card_${theme}.svg" \
              "https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=koki-develop&theme=${theme}"

            git add "./public/images/profile-summary-card_${theme}.svg"
          done

          if ! git diff --staged --exit-code; then
            git commit -m "Update Profile Summary Card"
            git push origin main
          fi
