name: Update Profile Summary Card

permissions: {}

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        theme:
          - github
          - github_dark
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update Profile Summary Card
        env:
          CARD_API_ENDPOINT: https://github-profile-summary-cards.vercel.app/api/cards/profile-details?username=koki-develop&theme=${{ matrix.theme }}
          CARD_THEME: ${{ matrix.theme }}
        run: |
          wget -q -O "./public/images/profile-summary-card_${CARD_THEME}.svg" "${CARD_API_ENDPOINT}"

          git add "./public/images/profile-summary-card_${CARD_THEME}.svg"
          if ! git diff --staged --exit-code; then
            git commit -m "Update Profile Summary Card"
            git push origin main
          fi
